### ISSUE TITLE
Label Missing for the fields of type Text (formatted, long)

### ISSUE THREAD

**Issue by nkgokul** [isramv/d8_materialize#9]
The labels are missing for the fields of type Text (formatted, long)

I am assuming it has something to do with the theme itself and not CKEditor as I don't see any javascript errors.

I will see if I can post a patch for the same.

**Comment by isramv** [comment]
Hi @nkgokul I changed the default base theme from `classy` to `false`, classy was giving me so many issues with added classes, please update your repo and see if that fixes your forms.
